[project]
name = "unit1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
	"stable-baselines3>=2.7.0",
	"swig>=4.3.1.post0",
	"gymnasium[box2d]>=1.2.1",
	"huggingface_sb3>=3.0",
	"pyvirtualdisplay>=3.0",
]
